### ISSUE TITLE
about the cars data

### ISSUE THREAD

**Issue by Usernamezhx** [PkuRainBow/Hard-Aware-Deeply-Cascaded-Embedding_release#6]
thanks for your code first.
The Cars dataset contains 16,185 images of 196 classes of cars. The data is split into 8,144 training images and 8,041 testing images
but the code show that:
`if choice == 'train':
        for i in range(0, 8054):
            cur_str = lines[i]
            split_str = cur_str.split(' ')
            image_str = (split_str[0]).split('/')
            cur_line = image_str[1] + " " + split_str[1] + "\n"
            file_w.write(cur_line)
        file_w.close()`
it has the 8054?

**Comment by PkuRainBow** [comment]
Please read the experimental parts of our paper. The training data contains 8054 images.
