### ISSUE TITLE
about the negative sample mining process, cascade or fixed?

### ISSUE THREAD

**Issue by bengouyy** [PkuRainBow/Hard-Aware-Deeply-Cascaded-Embedding_release#7]
I notice that you use the different 'hard_ratio' values in different branches(1.0, 0.5. 0.2) to control the negative sample mining process instead of selecting the failed sample from the previous cascade?

Is this a kind of approximation or I missed something?
Thanks

**Comment by PkuRainBow** [comment]
This a simple approximation.
